### ISSUE TITLE
[3.0.10] New reload checks cause scripts to not execute on the client in SMP, resulting in recipe desync between client and server

### ISSUE THREAD

**Issue by SargeRyong** [stanhebben/MineTweaker3#237]
Reproduced using MC 1.7.10, Minetweaker3 3.0.10.

I was testing a slew of complex recipe changes in my new tweaks file in SSP. Everything was working great, executed fine, all the recipes updated as expected.

Later, I deployed the scripts to my server to test them in SMP. (Note that the scripts were in the correct location in world/scripts server-side).

After connecting my client to the server, it became clear that the server HAD executed the scripts (e.g., furnaces would smelt things based on recipes I had added in the scripts), but the client had NOT executed them - none of the changes showed up locally.

As evidence, furnace recipes and TCon smeltery melting recipes that were added in the script functioned correctly, though the client's UI feedback said that they should not (recipes not present in NEI, the items in the smeltery appeared to be unmeltable, with no progress bar... until the server removed them from the inventory and added the metal to the tank).

I checked the changelog, since I saw that there was a new version out only a couple days ago and saw that there were some optimizations made to only reload scripts when absolutely necessary. Seeing this, I thought "aha, I bet the logic that determines when a reload is or isn't necessary is bugged", and downgraded to the previous version on both the client and server.

Immediately after downgrading to 3.0.9C, the scripts began reloading as expected and the issue went away.

**Comment by Haggle1996** [comment]
I can confirm this is also happening in my pack with 3.0.10

Haggle1996/RevolutionPack#90

**Comment by JasonMcRay** [comment]
One player of my pack InfiTech 2 also reportedthis issue. When playing on SMP the recipes in NEI are not changed visualy, but the recipe is.

Example:
I changed recipes for Iron Chest to require PLATES instead of INGOTS, on NEI, the recipe is shown to be made with ingots instead.
Problem is, when you try it with ingots, it doesn't work, but when you try the recipe with plates as it is supposed to work, no chest icon is shown in the output, but as soon as you click on the output slot, you get the chest.

**Comment by dirtyfargo** [comment]
I can also confirm that my scripts are not syncing properly server-side in version 3.0.10

**Comment by chorvus** [comment]
@JasonMcRay I am in the same server with the forum user that reported in the InfiTech 2 thread. I booted up an SMP world and after that everything was fixed both in SMP and the server world (until a client restart). Maybe that helps with debugging.

**Comment by Dream-Master** [comment]
The changed recipes are not shown but they working. If you start a singleplayer world and join back to the Server the recipes are shown correctly.
@stanhebben 
We need a quick fix here please bcause i change now all my scripts for GTTWeaker allready.

**Comment by JasonMcRay** [comment]
I have found slight workaround (works but can be annoying) for the time being. If you load Singleplayer the recipes will load. Then you join the server, recipes in NEI are still loaded thanks to the singleplayer.

**Comment by Dream-Master** [comment]
I send stan a message via Twitter and hope he will see it. After i take all Gregtech Tech Support to my GT Tweaker i change hundred of Recipes in my pack. Change this back would be more annoying so i hope we get a quick fix here.

**Comment by szernex** [comment]
Can also confirm, doing it the same way as JasonMcRay described works as a workaround.

**Comment by martindiv** [comment]
Having the same problem here. Looking at the minetweaker.log on the client side shows that the script is trying to run but is unable to find any of the resources for the recipes.

For instance: I've added an alternate recipe for Pistronics2's glue and see the following in the client side log:
ERROR: pistronics2-glue-alternate.zs:1: Could not resolve <Pistronics2 : Glue>
ERROR: pistronics2-glue-alternate.zs:1: Could not resolve <minecraft : slime_ball>
ERROR: pistronics2-glue-alternate.zs:1: Could not resolve <minecraft : slime_ball>
ERROR: pistronics2-glue-alternate.zs:1: Could not resolve <minecraft : sugar>
ERROR: pistronics2-glue-alternate.zs:1: Could not resolve <minecraft : dye : 15>
ERROR: Error executing pistronics2-glue-alternate.zs: null
java.lang.NullPointerException
        at minetweaker.mc1710.recipes.RecipeConverter.getIngredientType(RecipeConverter.java:39)
        at minetweaker.mc1710.recipes.RecipeConverter.getRecipeType(RecipeConverter.java:52)
        at minetweaker.mc1710.recipes.RecipeConverter.convert(RecipeConverter.java:59)
        at minetweaker.mc1710.recipes.MCRecipeManager.addShapeless(MCRecipeManager.java:118)
        at Pistronics2-glue-alternate.__script__(pistronics2-glue-alternate.zs:1)
        at __ZenMain__.run(pistronics2-glue-alternate.zs)

The script is just one line:
recipes.addShapeless(<Pistronics2:Glue>, [<minecraft:slime_ball>, <minecraft:slime_ball>, <minecraft:sugar>, <minecraft:dye:15>]);

This exact same script does not throw an error server side.

**Comment by Sunconure11** [comment]
I'm having the same issue. Does anyone have a workaround?

**Comment by jaredlll08** [comment]
Anyone able to test a version for me a bit later? I think I fixed it.

**Comment by Dream-Master** [comment]
Sure be back home in a min

**Comment by Dream-Master** [comment]
@jaredlll08 If it is a pre Version you can send it me via email dream-master@gmx,net or via dropbox.....
I have access to a server where i can test the server behaviours.

**Comment by jaredlll08** [comment]
Here try this:
http://www.blamejared.com/content/MineTweaker3-1.7.10-3.0.10_ALPHA.jar

**Comment by dirtyfargo** [comment]
@jaredlll08 I am unfortunately still having the same issue with my scripts not syncing properly server side with that release

**Comment by Dream-Master** [comment]
@jaredlll08 
Sorry but i have still the same issue. This version not fixing the problem.

**Comment by mrammy** [comment]
@Dream-Master and @dirtyfargo try this version: https://www.mediafire.com/?7oqsx0x6qb2g7vx

**Comment by Dream-Master** [comment]
@mrammy 
Ok i will test this version on my server.

**Comment by Dream-Master** [comment]
@mrammy Ok works nice. I think @jaredlll08 will add this too.
Thanks

**Comment by jaredlll08** [comment]
Fixed in #243

**Comment by ExDomino** [comment]
I still have this issue with the version 3.0.10B on my server. I have to do "/mt reload" in order to players that are currently logged in can see my recipe changes, but when they logout and login again, the changes made by my script are gone.
