### ISSUE TITLE
MineTweaker3 Scripting Issues... Please help!

### ISSUE THREAD

**Issue by ghost** [stanhebben/MineTweaker3#404]
Hello, I'm very new to the MineTweaker3 scripting so I will be very happy if someone can help me with this. By the way, I'm using MineTweaker for 1.10
When I use my script it says this:
ERROR: MineTweakerRecipieMaker.zs:27 > No such static member in minetweaker.item.IIngredient: SurvivalGenerator
ERROR: Error executing MineTweakerRecipieMaker.zs: null

I'm using these lines of code:
//#MARKER ADD
val Machine = <extrautils2:Machine>;
val SurvivalGenerator = Machine.withTag({Type:"extrautils2:generator_survival"});
//#MARKER REMOVE SHAPED
recipes.removeShaped(SurvivalGenerator, [[<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>], [<ore:cobblestone>, <minecraft:iron_ingot>, <ore:cobblestone>], [<minecraft:redstone>, <minecraft:furnace>, <minecraft:redstone>]]);

And here is the full script on paste bin: http://pastebin.com/6zwTRGiX

**Comment by Techlone** [comment]
`SurvivalGenerator` used before its declaration

**Comment by ghost** [comment]
Sorry Techlone, but how can I fix that? And can you explain to me what is the problem in better detail. Thanks!

**Comment by ghost** [comment]
OK, I did this:
//#MARKER ADD
import minetweaker.item.IIngredient;SurvivalGenerator;
val Machine = [<extrautils2:Machine>.onlyWithTag({Type:"extrautils2:generator_survival"})] as IIngredient[SurvivalGenerator];

But now I get this:
ERROR: Error parsing MineTweakerRecipieMaker.zs:31 -- Invalid expression, last token: import

Can someone please tell me what is the problem?
Also please explain to me how to fix the problem because I'm very new at the MineTweaker scripting thing..

**Comment by jaredlll08** [comment]
You cannot use a variable before you have declared it.

The error you are getting now is because imports have to be at the top of
the file. Please read the wiki as it should clear most if not all of your
questions up.

**Comment by ghost** [comment]
Thanks for the help jaredlll08! I fixed the problem with the import variable, but now I get this:
ERROR: Error parsing MineTweakerRecipeMaker.zs:12 -- ; expected

I have encountered this problem before, but it was a really easy fix, now I just can't seem to fix it.
Here is the script: http://pastebin.com/cA0M4ZG7

Can someone please fix the script for me?

**Comment by jaredlll08** [comment]
You have still not read the wiki at all. Please read the wiki or else I can't help you.

**Comment by ghost** [comment]
Well I got rid of my problem. So.......... yeah, I guess that's it...
